### ISSUE TITLE
Trouble reproducing results for Traffic Junction medium and hard

### ISSUE THREAD

**Issue by kenziyuliu** [hsvgbkhgbv/SQDDPG#17]
Hi,

Thanks for open sourcing your work! At the moment, I'm trying to reproduce Table 2 of your paper for traffic_junction medium settings; however, my reproduced numbers are only around 70% as opposed to around 88%.

To summarize my steps:
- I cloned your repo
- went to `args/traffic_junction_sqddpg.py` and set `max_steps=40` and `train_episodes_num=int(1e3)` according to Table 2 caption
- went to `environments/traffic_junction_env.py` and set `self.difficulty = 'medium'`
- went to `train.sh` and set `EXP_NAME="traffic_junction_sqddpg"`
- and run `bash train.sh`

The result I got when testing 1000 episodes is
```
========== REUSLTS ==========
Episode: 1000
Mean Reward: -0.1270/0.1434
Mean Success: 0.7187/0.2734
Mean Turn: 40.0000/0.0000
```

Would you be able to share some details about your training configs for all of easy/medium/hard?

Thanks!

**Comment by kenziyuliu** [comment]
I seem to have missed Table 6 on the paper!

**Comment by kenziyuliu** [comment]
Hi,

I have followed the training configs in Table 6, and unfortunately, I was still not able to reproduce the results of `traffic_junction` medium and hard (Table 2).

Specifically, here are my changes:
- Medium
  - Clone repo
  - In `environments/traffic_junction_env.py`, set `self.difficulty = 'medium'`
  - In `train.sh`, set `EXP_NAME="traffic_junction_sqddpg"`
  - Train by `bash train.sh`
  - During test, set `--episodes 1000` for `test.py`, and set `max_steps=40`, and `bash test.sh`
- Hard
  - Clone repo
  - In `args/traffic_junction_sqddpg.py`, set `max_steps=100`, `train_episodes_num=2000`
  - In `train.sh`, set `EXP_NAME="traffic_junction_sqddpg"`
  - Train by `bash train.sh`
  - During test, set `--episodes 1000` for `test.py`, and set `max_steps=60`, and `bash test.sh`

However, I get the following test performance:
- Medium (reported 88.98%, got 60.87%):
```
========== REUSLTS ==========
Episode: 1000
Mean Reward: -0.2712/0.3222
Mean Success: 0.6087/0.2885
Mean Turn: 40.0000/0.0000
```
- Hard (reported 87.04%, got 59.52%):
```
========== REUSLTS ==========
Episode: 1000
Mean Reward: -0.1792/0.2122
Mean Success: 0.5952/0.2800
Mean Turn: 60.0000/0.0000
```

Could you please share how to reproduce the reported results in Table 2? Thank you!

**Comment by mikezhang95** [comment]
Thank you for following our work. To answer your question, Table 2 is the setting for test phase. For training, you should follow Table 6 in appendix.

**Comment by mikezhang95** [comment]
What is your training parameters for medium?

**Comment by kenziyuliu** [comment]
> What is your training parameters for medium?

Hi, thanks for the quick reply!  My steps are summarized in the above comment

**Comment by hsvgbkhgbv** [comment]
Hi, we have checked out our code and find the reason is that we changed the code later on. You can recover the result on the report by rolling back the code version as following script:
git fetch --all --tags
git checkout tags/SQDDPG_v1.0 -b v1.0

and run the experiment using our setups on the paper. The result should be revocered.

We wish this can help you.

**Comment by kenziyuliu** [comment]
Thanks! I will let you know if I run into other issues

**Comment by kenziyuliu** [comment]
Hi there, could you please update your master to include the correctly implemented Traffic Junction (medium/hard)? While your previous version v1.0 works (`git checkout tags/SQDDPG_v1.0 -b v1.0`), it has too many changes compared to your master for us to migrate our existing code (which is built on top of your master).

Since you have the best knowledge of what has been changed between v1.0 and master, it would be really great if you could make the corresponding fix in the master. Thank you!

**Comment by hsvgbkhgbv** [comment]
Hi,


Thank you for your advice! We will do it later.


Best,

Jianhong

kenziyuliu <notifications@github.com> 于 2020年5月8日周五 15:53写道：
