### ISSUE TITLE
Why do you just order the actions instead of states?

### ISSUE THREAD

**Issue by XuJing1022** [hsvgbkhgbv/SQDDPG#18]
After reading your paper, I have a question about Shapley Q value. In the paper and codes, I notice that you just order the action as the sampling permutation. Why not order the state together? Is it because of the worse performance?

Hoping for your answer :)

**Comment by hsvgbkhgbv** [comment]
Hi, thank you for your interest on our work.

Actually, we assume the state are shared among all agents always in our theorem. This is the main reason why we didn't permute state in the implementation.

 I think it could be a good question whether we can assume the partial observation. If we assume the partial observation, then we can permute state also and should mask the states that haven't appeared like the opration of actions. This is only my hypothesis and we haven't attempted it.

We wish this can help you!
