### ISSUE TITLE
How run train.py with maddpg & simple_tag?

### ISSUE THREAD

**Issue by zhaoyueplc** [hsvgbkhgbv/SQDDPG#20]
Hi,

Would anybody help on this issue?

I am running the train.py to see the scenario simple_tag with maddpg,  and have modified model_name = 'maddpg' in arguments.py
the error pops up:
Traceback (most recent call last):
  File "/home/zhaoyue/SQDDPG/utilities/trainer.py", line 9, in <module>
    from arguments import *
  File "/home/zhaoyue/SQDDPG/arguments.py", line 18, in <module>
    aux_args = AuxArgs[model_name](1)
TypeError: __new__() takes 1 positional argument but 2 were given

I have no idea how to resolve it.  And please help.

Thanks!

**Comment by hsvgbkhgbv** [comment]
Hi,


I suggest you follow the instructions in ReadMe file. If you would like to run maddpg, you just need to change the value of ```EXP_NAME ``` to ```"simple_tag_maddpg"```. If you need to have a remark for differenciating your experiments, you can give a value for ```ALIAS```, e.g., ```ALIAS=exp_1``` to indicate experiment 1.


Best,

Jianhong

**Comment by zhaoyueplc** [comment]
Hi Jianhong,
你好，我看了你们的readme了,但是sh文件并不方便debug。请问你们使用train.py的方式能跑simple_tag的maddpg吗？

**Comment by hsvgbkhgbv** [comment]
Hi,


I think you directly copy ```simple_tag_maddpg.py``` to ```arguments.py```, then it should work.


Best,

Jianhong
